name: music
description: "A simple Flutter project with bottom navigation and images"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # font_awesome_flutter: ^10.7.0
  audioplayers: ^6.5.0
  # url_launcher: ^6.2.6 # only if you plan to open URLs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - images/  # all images in this folder
    - assets/songs/

  fonts:
    - family: Edu
      fonts:
        - asset: fonts/EduNSWACTCursive-VariableFont_wght.ttf
