name: goal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.5.0
  rflutter_alert: ^2.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0   

flutter:

  uses-material-design: true

  assets:
    - assets/songs/
    - images/Austria - Bundesliga/
    - images/Questions/


  fonts:
    - family: Edu
      fonts:
        - asset: fonts/EduNSWACTCursive-VariableFont_wght.ttf

# flutter_native_splash:  
#   color: "#5B21B6"
#   image: images/football-soccer-icon.webp
#   android: true
#   ios: true

 